---
- hosts: all
  become: yes
  vars:
      sudoGroup: "{{ 'sudo' if ansible_distribution == 'Ubuntu' else 'wheel' }}"
  tasks:

   - name: Add user to remote hosts
     user: name=mentor groups=" {{ sudoGroup  }} " shell=/bin/bash

   - name: Add SSH keys to remote hosts
     authorized_key: user=mentor key="{{ lookup('file', "/etc/ansible/common/files/mentor/id_rsa.pub") }}"
